version: 2

sources:
  - name: public
    tables:
      - name: Person
        description: >
          People data including first name and last name.
      - name: Product
        description: >
          Product general information.
      - name: SalesOrderDetail
        description: >
          Details about all sales.
      - name: SalesOrderHeader
        description: >
          More specific order data.
      - name: SpecialOfferProduct
        description: >
          Special offer data.
      - name: Customer
        description: >
          Customer data.
